import type { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Generated by `pnpm migration:generate --name=KnowledgeBase` — diff of the entities
 * against ./data/mentro.db. Review before committing: generated diffs describe structural
 * changes, not data backfills (add those by hand if needed).
 */
export class KnowledgeBase1787780185568 implements MigrationInterface {
  name = "KnowledgeBase1787780185568";

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql);
  }
}

const UP: string[] = [
  'CREATE TABLE "groups" ("id" text PRIMARY KEY NOT NULL, "name" text NOT NULL, "parent_id" text, "sort_order" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))',
  'CREATE INDEX "idx_groups_parent" ON "groups" ("parent_id")',
  'DROP INDEX "idx_assets_status"',
  'DROP INDEX "idx_assets_source"',
  'DROP INDEX "uq_assets_path"',
  'CREATE TABLE "temporary_assets" ("id" text PRIMARY KEY NOT NULL, "source_id" text NOT NULL, "path" text NOT NULL, "size_bytes" integer NOT NULL, "mtime_ms" integer NOT NULL, "content_hash" text, "mime" text, "kind" text NOT NULL, "extraction_status" text NOT NULL DEFAULT (\'pending\'), "extraction_version" integer, "extracted_at" datetime, "error" text, "oversized" boolean NOT NULL DEFAULT (0), "group_id" text, "uploaded_at" datetime, "uploaded_by" text)',
  'INSERT INTO "temporary_assets"("id", "source_id", "path", "size_bytes", "mtime_ms", "content_hash", "mime", "kind", "extraction_status", "extraction_version", "extracted_at", "error", "oversized") SELECT "id", "source_id", "path", "size_bytes", "mtime_ms", "content_hash", "mime", "kind", "extraction_status", "extraction_version", "extracted_at", "error", "oversized" FROM "assets"',
  'DROP TABLE "assets"',
  'ALTER TABLE "temporary_assets" RENAME TO "assets"',
  'CREATE INDEX "idx_assets_status" ON "assets" ("extraction_status")',
  'CREATE INDEX "idx_assets_source" ON "assets" ("source_id")',
  'CREATE UNIQUE INDEX "uq_assets_path" ON "assets" ("path")',
];

const DOWN: string[] = [
  'DROP TABLE "groups"',
  'DROP INDEX "idx_groups_parent"',
  'CREATE INDEX "idx_assets_status" ON "assets" ("extraction_status")',
  'CREATE INDEX "idx_assets_source" ON "assets" ("source_id")',
  'CREATE UNIQUE INDEX "uq_assets_path" ON "assets" ("path")',
  'DROP TABLE "temporary_assets"',
  'INSERT INTO "assets"("id", "source_id", "path", "size_bytes", "mtime_ms", "content_hash", "mime", "kind", "extraction_status", "extraction_version", "extracted_at", "error", "oversized") SELECT "id", "source_id", "path", "size_bytes", "mtime_ms", "content_hash", "mime", "kind", "extraction_status", "extraction_version", "extracted_at", "error", "oversized" FROM "temporary_assets"',
  'CREATE TABLE "assets" ("id" text PRIMARY KEY NOT NULL, "source_id" text NOT NULL, "path" text NOT NULL, "size_bytes" integer NOT NULL, "mtime_ms" integer NOT NULL, "content_hash" text, "mime" text, "kind" text NOT NULL, "extraction_status" text NOT NULL DEFAULT (\'pending\'), "extraction_version" integer, "extracted_at" datetime, "error" text, "oversized" boolean NOT NULL DEFAULT (0))',
  'ALTER TABLE "assets" RENAME TO "temporary_assets"',
  'DROP INDEX "idx_assets_status"',
  'DROP INDEX "idx_assets_source"',
  'DROP INDEX "uq_assets_path"',
];
