import type { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Generated by `pnpm migration:generate --name=IntelligenceLayer` — diff of the entities
 * against ./data/mentro.db. Review before committing: generated diffs describe structural
 * changes, not data backfills (add those by hand if needed).
 */
export class IntelligenceLayer1788113759723 implements MigrationInterface {
  name = "IntelligenceLayer1788113759723";

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql);
  }
}

const UP: string[] = [
  'CREATE TABLE "unit_embeddings" ("unit_id" text PRIMARY KEY NOT NULL, "asset_id" text NOT NULL, "dim" integer NOT NULL, "vector" blob NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))',
  'CREATE INDEX "idx_unit_embeddings_asset" ON "unit_embeddings" ("asset_id")',
  'DROP INDEX "idx_jobs_asset"',
  'DROP INDEX "idx_jobs_status"',
  'CREATE TABLE "temporary_jobs" ("id" text PRIMARY KEY NOT NULL, "asset_id" text, "kind" text NOT NULL, "status" text NOT NULL, "attempts" integer NOT NULL DEFAULT (0), "error_code" text, "error" text, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "payload" text)',
  'INSERT INTO "temporary_jobs"("id", "asset_id", "kind", "status", "attempts", "error_code", "error", "created_at", "updated_at") SELECT "id", "asset_id", "kind", "status", "attempts", "error_code", "error", "created_at", "updated_at" FROM "jobs"',
  'DROP TABLE "jobs"',
  'ALTER TABLE "temporary_jobs" RENAME TO "jobs"',
  'CREATE INDEX "idx_jobs_asset" ON "jobs" ("asset_id")',
  'CREATE INDEX "idx_jobs_status" ON "jobs" ("status")',
];

const DOWN: string[] = [
  'DROP TABLE "unit_embeddings"',
  'DROP INDEX "idx_jobs_asset"',
  'DROP INDEX "idx_jobs_status"',
  'CREATE TABLE "temporary_jobs" ("id" text PRIMARY KEY NOT NULL, "asset_id" text, "kind" text NOT NULL, "status" text NOT NULL, "attempts" integer NOT NULL DEFAULT (0), "error_code" text, "error" text, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "updated_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))',
  'INSERT INTO "temporary_jobs"("id", "asset_id", "kind", "status", "attempts", "error_code", "error", "created_at", "updated_at") SELECT "id", "asset_id", "kind", "status", "attempts", "error_code", "error", "created_at", "updated_at" FROM "jobs"',
  'DROP TABLE "jobs"',
  'ALTER TABLE "temporary_jobs" RENAME TO "jobs"',
  'CREATE INDEX "idx_jobs_asset" ON "jobs" ("asset_id")',
  'CREATE INDEX "idx_jobs_status" ON "jobs" ("status")',
];
