import type { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Generated by `pnpm migration:generate --name=Acl` — diff of the entities
 * against ./data/mentro.db. Review before committing: generated diffs describe structural
 * changes, not data backfills (add those by hand if needed).
 */
export class Acl1789628690218 implements MigrationInterface {
  name = "Acl1789628690218";

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql);
  }
}

const UP: string[] = [
  'CREATE TABLE "permissions" ("id" text PRIMARY KEY NOT NULL, "subject_type" text NOT NULL, "subject_id" text NOT NULL, "target_type" text NOT NULL, "target_id" text NOT NULL, "level" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), CONSTRAINT "uq_perm_subject_target" UNIQUE ("subject_type", "subject_id", "target_type", "target_id"))',
  'CREATE INDEX "idx_perm_subject" ON "permissions" ("subject_type", "subject_id")',
  'CREATE INDEX "idx_perm_target" ON "permissions" ("target_type", "target_id")',
  'CREATE TABLE "user_groups" ("id" text PRIMARY KEY NOT NULL, "name" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), CONSTRAINT "uq_user_groups_name" UNIQUE ("name"))',
  'CREATE TABLE "user_group_members" ("user_id" text NOT NULL, "group_id" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), PRIMARY KEY ("user_id", "group_id"))',
  'CREATE INDEX "idx_ugm_group" ON "user_group_members" ("group_id")',
  'CREATE INDEX "idx_ugm_user" ON "user_group_members" ("user_id")',
  'DROP INDEX "idx_groups_parent"',
  'CREATE TABLE "temporary_groups" ("id" text PRIMARY KEY NOT NULL, "name" text NOT NULL, "parent_id" text, "sort_order" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), "visibility" text NOT NULL DEFAULT (\'internal\'))',
  'INSERT INTO "temporary_groups"("id", "name", "parent_id", "sort_order", "created_at") SELECT "id", "name", "parent_id", "sort_order", "created_at" FROM "groups"',
  'DROP TABLE "groups"',
  'ALTER TABLE "temporary_groups" RENAME TO "groups"',
  'ALTER TABLE "assets" ADD COLUMN "visibility" text NOT NULL DEFAULT (\'internal\')',
  'CREATE INDEX "idx_groups_parent" ON "groups" ("parent_id")',
];

const DOWN: string[] = [
  'ALTER TABLE "assets" DROP COLUMN "visibility"',
  'DROP TABLE "permissions"',
  'DROP INDEX "idx_perm_subject"',
  'DROP INDEX "idx_perm_target"',
  'DROP TABLE "user_groups"',
  'DROP TABLE "user_group_members"',
  'DROP INDEX "idx_ugm_group"',
  'DROP INDEX "idx_ugm_user"',
  'CREATE INDEX "idx_groups_parent" ON "groups" ("parent_id")',
  'DROP TABLE "temporary_groups"',
  'INSERT INTO "groups"("id", "name", "parent_id", "sort_order", "created_at") SELECT "id", "name", "parent_id", "sort_order", "created_at" FROM "temporary_groups"',
  'CREATE TABLE "groups" ("id" text PRIMARY KEY NOT NULL, "name" text NOT NULL, "parent_id" text, "sort_order" integer NOT NULL DEFAULT (0), "created_at" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))',
  'ALTER TABLE "groups" RENAME TO "temporary_groups"',
  'DROP INDEX "idx_groups_parent"',
];
