import type { MigrationInterface, QueryRunner } from "typeorm";

/**
 * Generated by `pnpm migration:generate --name=HiddenSlides` — diff of the entities
 * against ./data/mentro.db. Review before committing: generated diffs describe structural
 * changes, not data backfills (add those by hand if needed).
 */
export class HiddenSlides1790664873335 implements MigrationInterface {
  name = "HiddenSlides1790664873335"

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql);
  }
}

const UP: string[] = [
  "DROP INDEX \"idx_content_units_asset\"",
  "DROP INDEX \"uq_content_units_asset_ordinal_type\"",
  "CREATE TABLE \"temporary_content_units\" (\"id\" text PRIMARY KEY NOT NULL, \"asset_id\" text NOT NULL, \"ordinal\" integer NOT NULL, \"unit_type\" text NOT NULL, \"title\" text, \"text\" text, \"start_ms\" integer, \"end_ms\" integer, \"thumb_path\" text, \"meta_json\" text, \"hidden\" boolean NOT NULL DEFAULT (0))",
  "INSERT INTO \"temporary_content_units\"(\"id\", \"asset_id\", \"ordinal\", \"unit_type\", \"title\", \"text\", \"start_ms\", \"end_ms\", \"thumb_path\", \"meta_json\") SELECT \"id\", \"asset_id\", \"ordinal\", \"unit_type\", \"title\", \"text\", \"start_ms\", \"end_ms\", \"thumb_path\", \"meta_json\" FROM \"content_units\"",
  "DROP TABLE \"content_units\"",
  "ALTER TABLE \"temporary_content_units\" RENAME TO \"content_units\"",
  "CREATE INDEX \"idx_content_units_asset\" ON \"content_units\" (\"asset_id\")",
  "CREATE UNIQUE INDEX \"uq_content_units_asset_ordinal_type\" ON \"content_units\" (\"asset_id\", \"ordinal\", \"unit_type\")",
]

const DOWN: string[] = [
  "CREATE INDEX \"idx_content_units_asset\" ON \"content_units\" (\"asset_id\")",
  "CREATE UNIQUE INDEX \"uq_content_units_asset_ordinal_type\" ON \"content_units\" (\"asset_id\", \"ordinal\", \"unit_type\")",
  "DROP TABLE \"temporary_content_units\"",
  "INSERT INTO \"content_units\"(\"id\", \"asset_id\", \"ordinal\", \"unit_type\", \"title\", \"text\", \"start_ms\", \"end_ms\", \"thumb_path\", \"meta_json\") SELECT \"id\", \"asset_id\", \"ordinal\", \"unit_type\", \"title\", \"text\", \"start_ms\", \"end_ms\", \"thumb_path\", \"meta_json\" FROM \"temporary_content_units\"",
  "CREATE TABLE \"content_units\" (\"id\" text PRIMARY KEY NOT NULL, \"asset_id\" text NOT NULL, \"ordinal\" integer NOT NULL, \"unit_type\" text NOT NULL, \"title\" text, \"text\" text, \"start_ms\" integer, \"end_ms\" integer, \"thumb_path\" text, \"meta_json\" text)",
  "ALTER TABLE \"content_units\" RENAME TO \"temporary_content_units\"",
  "DROP INDEX \"idx_content_units_asset\"",
  "DROP INDEX \"uq_content_units_asset_ordinal_type\"",
]
